from django.urls import path
from page_html.views import home,asset,assetoverview,assetcapture,assetcapturehardwarecontain,assetcapturelicensecontain,assetcapturecorelicensecontain,assetcapturesoftwarecontain,project,projectoverview,projectworkspace,finance,inventory,report,team,teamoverviews,teamlistviews,teamadd,clients,clientsoverviews,clientslistviews,clientsadd,suppliers,suppliersoverview,supplierlistview,supplieradd,classification,classificationlocation,classificationunit,classificationstatus,classificationcategory,setting,support,taskglobal,notesglobal,uploadglobal,settingprofile,settingpassword,settingnotification,settingauthentication,forgetpassword,validity
urlpatterns = [
    path('', home,name='home'),
    path('asset/', asset,name='asset'),
    path('assetoverview/', assetoverview,name='assetoverview'),
    path('assetcapture/', assetcapture,name='assetcapture'),
    path('assetcapturehardwarecontain/', assetcapturehardwarecontain,name='assetcapturehardwarecontain'),
    path('assetcapturesoftwarecontain/', assetcapturesoftwarecontain,name='assetcapturesoftwarecontain'),
    path('assetcapturelicensecontain/', assetcapturelicensecontain,name='assetcapturelicensecontain'),
    path('assetcapturecorelicensecontain/', assetcapturecorelicensecontain,name='assetcapturecorelicensecontain'),
    path('project/', project,name='project'),
    path('projectoverview/', projectoverview,name='projectoverview'),
    path('projectworkspace/', projectworkspace,name='projectworkspace'),
    path('finance/', finance,name='finance'),
    path('inventory/', inventory,name='inventory'),
    path('report/', report,name='report'),
    path('team/', team,name='team'),
    path('teamoverviews/', teamoverviews,name='teamoverviews'),
    path('teamlistviews/', teamlistviews,name='teamlistviews'),
    path('teamadd/', teamadd,name='teamadd'),
    path('clients/', clients,name='clients'),
    path('clientsoverviews/', clientsoverviews,name='clientsoverviews'),
    path('clientslistviews/', clientslistviews,name='clientslistviews'),
    path('clientsadd/', clientsadd,name='clientsadd'),
    path('suppliers/', suppliers,name='suppliers'),
    path('suppliersoverview/', suppliersoverview,name='suppliersoverview'),
    path('supplierlistview/', supplierlistview,name='supplierlistview'),
    path('supplieradd/', supplieradd,name='supplieradd'),
    path('classification/', classification,name='classification'),
    path('classificationlocation/', classificationlocation,name='classificationlocation'),
    path('classificationunit/', classificationunit,name='classificationunit'),
    path('classificationstatus/', classificationstatus,name='classificationstatus'),
    path('classificationcategory/', classificationcategory,name='classificationcategory'),
    path('setting/', setting,name='setting'),
    path('settingprofile/', settingprofile,name='settingprofile'),
    path('settingpassword/', settingpassword,name='settingpassword'),
    path('forgetpassword/', forgetpassword,name='forgetpassword'),
    path('settingnotification/', settingnotification,name='settingnotification'),
    path('settingauthentication/', settingauthentication,name='settingauthentication'),
    path('support/', support,name='support'),
    path('taskglobal/', taskglobal,name='taskglobal'),
    path('notesglobal/', notesglobal,name='notesglobal'),
    path('uploadglobal/', uploadglobal,name='uploadglobal'),
    path('validity/', validity,name='validity'),  


]
